### PR TITLE
unalias remove_entry_secure and implement proper call to rm_rf

### PR DESCRIPTION
**Pull request by gnikonorov**
Change `remove_entry_secure` from alias of `rm_rf` to a call of `rm_rf` with proper arguments to remedy issue noted in https://github.com/fakefs/fakefs/issues/396.

### CODE REVIEW

**Comment by grosser** [comment]
looks about right, can you add a test that fails without these changes ?

**Comment by gnikonorov** [comment]
Of course, they've been added in.

**Comment by grosser** [comment]
awesome! ✨

**Comment by grosser** [comment]
0.14.3

**Pull request merged**
