### PR TITLE
Implement readable? and writable? methods

### PR DESCRIPTION
**Pull request by gnikonorov**
Resolution to issue https://github.com/fakefs/fakefs/issues/308, implement proper `readable?` and `writable?` methods.

### CODE REVIEW

**Comment by gnikonorov** [comment]
This is behaving badly when I do local testing outside `bundler`. Will investigate and hold off on merging until corrected.

**Comment by gnikonorov** [comment]
I fixed my issue - I incorrectly ordered `user`, `group`, `world` precedence. I'll merge this in after I write some good tests for it.

**Comment by gnikonorov** [comment]
Issue fixed. @grosser would you mind taking another look before I merge?

**Comment by gnikonorov** [comment]
@grosser - I don't think I'll be making any more changes to `fakefs` for a few days. It may be a good time to do a release if you have the time.

**Comment by grosser** [comment]
0.17.0 🎉

**Pull request merged**
