### PR TITLE
make fakefs recognize dot files in globs when asked

### PR DESCRIPTION
**Pull request by gnikonorov**
Resolution for https://github.com/fakefs/fakefs/issues/314, add in `File::FNM_DOTMATCH` option for `Dir.glob`

### CODE REVIEW

**Comment by gnikonorov** [comment]
@grosser: It looks like Travis' `rubocop` has changed? Looks like mutiple test files are failing unrelated to this pull request.

**Comment by grosser** [comment]
it's pinned to the minor version ... feel free to pin it to the patch or fix them if it's easy

**Comment by grosser** [comment]
looks like a bug ... pin it to 0.56.0 :)

**Comment by grosser** [comment]
in the gemspec

**Comment by gnikonorov** [comment]
Looks like that didn't do the trick, unless I specified the version wrong:
```
spec.add_development_dependency 'rubocop', '0.56.0'
```

**Comment by gnikonorov** [comment]
I can update everything to make rubocop pass tomorrow, it is late here.

**Comment by gnikonorov** [comment]
I'm still trying to figure out why this is failing. Locally, running `rubocop` passes in the `tests` directory with both the latest version of `rubocop` and the version `Travis` is using. However, I do feel bad ignoring this one as it is a [valid rubocop error](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Layout/SpaceBeforeFirstArg).

I'll look at what's changed between passing runs of `Travis` and this run.

Local testing ( with `rubocop` used by `Travis`):
```
✔ ~/projects/fakefs [issue_314|…16]
20:30 $ bundle exec rubocop
Inspecting 39 files
.......................................

39 files inspected, no offenses detected
✔ ~/projects/fakefs [issue_314|…16]
20:30 $ bundle exec rubocop -v
0.56.0
✔ ~/projects/fakefs [issue_314|…16]
20:30 $
```

Local testing (with latest `rubocop`):
```
✘-1 ~/projects/fakefs [issue_314|…16]
20:31 $ cd test/
✔ ~/projects/fakefs/test [issue_314|…16]
20:31 $ rubocop
Inspecting 16 files
................

16 files inspected, no offenses detected
✔ ~/projects/fakefs/test [issue_314|…16]
20:31 $ rubocop -v
0.58.1
✔ ~/projects/fakefs/test [issue_314|…16]
20:31 $
```

It's interesting to note that `rubocop` is constantly assigning blame to lines like this: `class PathnameTest < Minitest::Test` but the cop is in regards to methods.

**Comment by gnikonorov** [comment]
The only different I could find is the version of the `parser` gem:

In a [working](https://travis-ci.org/fakefs/fakefs/jobs/401562867) `Travis` build: `parser 2.5.1.0`
In a [broken](https://travis-ci.org/fakefs/fakefs/jobs/402052252) build: `parser 2.5.1.1`

**Comment by grosser** [comment]
awesome cleanup!

**Comment by grosser** [comment]
0.16.0

**Pull request merged**
