### PR TITLE
Ruby 3.2 removes the File.exists? alias

### PR DESCRIPTION
**Pull request by jweir**
The method was deprecated since Ruby 2.2

https://docs.ruby-lang.org/en/2.2.0/File.html#method-c-exists-3F

### CODE REVIEW

**Comment by jweir** [comment]
We came across this with some tests that should have been erroring when calling File.exists? but passed.

Might be simpler to remove the alias to exists? – it has been deprecated since the first term of the Obama administration.

**Comment by grosser** [comment]
It's clearly Obamas fault so let's remove the alias :)

**Comment by grosser** [comment]
CI is not happy 😞

**Comment by jweir** [comment]
CI is happy now.

Alias removed – this would be a breaking change for the people preferring plurals. 

Let me know if you would like it squashed.

**Comment by grosser** [comment]
2.0.0

**Pull request merged**
