### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
http://github.com/defunkt/fakefs | https://github.com/fakefs/fakefs 
http://github.com/defunkt/fakefs/issues | https://github.com/fakefs/fakefs/issues 

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://help.github.com/forking/ | https://help.github.com/forking/ 
http://help.github.com/send-pull-requests/ | https://help.github.com/send-pull-requests/ 
http://rubygems.org/ | https://rubygems.org/ 
http://rubygems.org/gems/fakefs | https://rubygems.org/gems/fakefs 

### Other Corrected URLs 
Was | Now 
--- | --- 
http://rdoc.info/github/defunkt/fakefs | http://www.rubydoc.info/github/defunkt/fakefs 
http://travisci.org/#!/defunkt/fakefs | https://travis-ci.org/#!/defunkt/fakefs

### CODE REVIEW

**Comment by grosser** [comment]
Nice!

**Comment by ReadmeCritic** [comment]
:smile:

**Comment by ReadmeCritic** [comment]
hey @grosser frankenstein (and awesome_bot) use `parallel` :tada:

**Comment by grosser** [comment]
Glad it's used for good :)

**Pull request merged**
