### PR TITLE
Add tests for Temfile and IO interaction

### PR DESCRIPTION
**Pull request by ekohl**
While trying to debug a hard to trace error where a Tempfile was created and then read with IO.foreach, I couldn't explain it. I first started with a regular minitest reproducer but failed. I then tried to write a similar test in the original project which was using rspec. There I could instantly reproduce it. Copying the same test to FakeFS also worked which means it must be something with the RSpec interaction.

At this point I'm stuck and can't explain why this is but a reproducer should make it easier for a FakeFS developer to debug.

This is a follow up to https://github.com/fakefs/fakefs/pull/441#issuecomment-615850531

### CODE REVIEW

**Comment by grosser** [comment]
- Tempfile.create should not require to create the folder, fixing this here https://github.com/fakefs/fakefs/pull/445
- IO is not stubbed ... nothing to do with rspec

**Comment by grosser** [comment]
does https://github.com/fakefs/fakefs/pull/446 work ?

**Comment by ekohl** [comment]
> Tempfile.create should not require to create the folder, fixing this here #445

Thanks!

> IO is not stubbed ... nothing to do with rspec

But it is weird that it works in minitest but not in rspec, as I think my tests show. Any idea why?

> does #446 work ?

Will comment there.

**Comment by ekohl** [comment]
I ended up disabling FakeFS in that particular test and use the regular methods to create a temporary directory.

**Pull request closed without merging**
