### PR TITLE
revert encoding removal

### PR DESCRIPTION
**Pull request by grosser**
see https://github.com/fakefs/fakefs/issues/373
introduced in https://github.com/fakefs/fakefs/commit/5c22767bdace27531e32a50cffb8128d00a24759

@voxik @acant

### CODE REVIEW

**Comment by acant** [comment]
@voxik thanks for spotting this, I did not appreciate the difference between default_external and the default_internal.

Unfortunately, Encoding.default_external= docs say that it should not be used in code:
https://ruby-doc.org/core-2.2.0/Encoding.html#method-c-default_external-3D
And that it should be set using the -E flag instead.
And it shows a deprecating message when the warnings are turned on.

But maybe this is a case where it is needed, and a commented is needed to explain why and to help fixing it if the method is removed in the future.
Or if the testsuite is going to depend upon UTF-8 encoding, maybe -E could be added to the test/spec tasks in the Rakefile?

**Comment by grosser** [comment]
added a silence-warnings block ... good enough for now ... if it ever becomes a real issue we can spend more time on it ... more urgent to have a reliable test suite :D

**Comment by acant** [comment]
Sounds like a good compromise. And hopefully these comments/issue/PR will provide some guidance in the future if Encoding.default_external does get removed in the future.

**Comment by voxik** [comment]
May be external process could be spawned to test this properly ....

**Comment by acant** [comment]
@voxik that sounds like a good idea. Having tests for each of cases that you described in #373 would be great.

**Pull request merged**
