### PR TITLE
simplify git workflow

### PR DESCRIPTION
**Pull request by grosser**

### CODE REVIEW

**Comment by grosser** [comment]
@smtlaissezfaire

**Comment by smtlaissezfaire** [comment]
Agreed with your general idea - let's update the README so it's documented. 

The bump library is new to me. Good idea.

A few comments/questions: 

1. Just minor build failures re: rubocop need to be fixed
2.Does the contributors file get committed?

(I haven't tried running it)

**Comment by grosser** [comment]
yep it gets committed since bump does a commit

**Comment by smtlaissezfaire** [comment]
Ok - otherwise seems good to me (aside from the rubocop failure).  I'll let
you merge.

Thanks @grosser!

Best,

Scott Taylor
Oakland Note LLC

**Comment by smtlaissezfaire** [comment]
👍

**Pull request merged**
