### PR TITLE
Support ::File#readpartial by forwarding to StringIO implem

### PR DESCRIPTION
**Pull request by Annih**

### CODE REVIEW

**Comment by Annih** [comment]
@grosser it seems the test suite broke between my IO patch and the 1.7.0 release, is it related to my changes?
See https://github.com/fakefs/fakefs/runs/6956111942?check_suite_focus=true

**Comment by grosser** [comment]
nah, some order-dependent foobar I hope ... can be fixed another time

**Comment by grosser** [comment]
a test that uses it ?

**Comment by grosser** [comment]
found it ... 
```
SEED=31631 ruby -w -I"lib" /Users/mgrosser/Code/tools/fakefs/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb "test/dir/tempfile_test.rb" "test/fake/file/join_test.rb" "test/fake/file/lstat_test.rb" "test/fake/file/stat_test.rb" "test/fake/file/sysseek_test.rb" "test/fake/file/syswrite_test.rb" "test/fake/file_test.rb" "test/fake/symlink_test.rb" "test/fakefs_test.rb" "test/file/stat_test.rb" "test/globber_test.rb" "test/kernel_test.rb" "test/pathname_test.rb" "test/safe_test.rb" -v
```

fixed in master

**Comment by Annih** [comment]
Rebased on top of #477 to pass tests.

**Comment by grosser** [comment]
lmk if you want a new release

**Comment by Annih** [comment]
Thanks a lot for your quick answers, reviews, etc!

I can wait at least for #475 to be merged :)

**Pull request merged**
