### PR TITLE
Add ino to directories

### PR DESCRIPTION
**Pull request by gnikonorov**
Partial resolution for issue https://github.com/fakefs/fakefs/issues/321; add the ino method for `File::Stat` for directories. Support for `File::Stat` for files was added in pull request https://github.com/fakefs/fakefs/pull/408.

### CODE REVIEW

**Comment by grosser** [comment]
looks good!

**Comment by grosser** [comment]
let me know when you are done / want a release

**Comment by grosser** [comment]
the test-cases would be easier to read if they were shorter/more focussed

**Comment by gnikonorov** [comment]
Thank you @grosser, this should cover the `ino` method for all file system objects now. I don't mind when the release occurs, this pull request will function fine as long as it's coupled with pull request https://github.com/fakefs/fakefs/pull/408.

It looks like the build failed when this was merged into master: https://travis-ci.org/fakefs/fakefs/jobs/401569435. I'm not too familiar with Travis, but it looks like an internal issue and re-running it should work just fine?

**Comment by grosser** [comment]
yeah, PR was green so I'm not worried

**Comment by grosser** [comment]
0.15.0

**Pull request merged**
