### PR TITLE
Resolve issues with Pathname objects, Globber#regexp and the new Rails 4.2.5.1 glob pattern

### PR DESCRIPTION
**Pull request by tovodeverett**
This pull request supersedes https://github.com/fakefs/fakefs/pull/330 and is rebased against current master.

### CODE REVIEW

**Comment by grosser** [comment]
@dtognazzini @smtlaissezfaire good to merge ?

**Comment by grosser** [comment]
I like it ... so here goes nothing ...

**Comment by grosser** [comment]
v0.9.0

**Comment by grosser** [comment]
and now we wait for the fallout :D

**Comment by tovodeverett** [comment]
Thanks!  I'm back on the published `fakefs` for my Rails app and everything is working.

There is one outstanding issue that I created to address a request from @dtognazzini.  Issue #332 is in relationship to more complicated globbing syntax, namely something like `Dir['{,*,*/*}.rb']`.  It will probably be a while before I can work on it, but if I decide to attack the issue is there some sort of consensus that a robust implementation with comprehensive tests that aims for 100% compatibility with http://ruby-doc.org/core-2.3.0/Dir.html#method-c-glob would be worth merging?

**Comment by grosser** [comment]
I'd say fix whatever issue you can unless it adds a ton of complexity /
performance overhead ...

On Wed, Jun 29, 2016 at 9:32 PM, Toby Ovod-Everett <notifications@github.com

**Comment by tovodeverett** [comment]
I'm jumping this thread to the #332.

**Pull request merged**
