### PR TITLE
Resolve issues with Pathname objects, Globber#regexp and the new Rails 4.2.5.1 glob pattern

### PR DESCRIPTION
**Pull request by tovodeverett**
This should address issues https://github.com/fakefs/fakefs/issues/326 and https://github.com/fakefs/fakefs/issues/328, as well as mixing in pull request https://github.com/fakefs/fakefs/pull/325.

### CODE REVIEW

**Comment by smtlaissezfaire** [comment]
What is the rails 4.2.5 glob pattern? I'd consider merging this as it seems ito resolve a lot of issues, but want some context first.

**Comment by tovodeverett** [comment]
In an earlier variant, I left it expanded with `/x` and had it assigned to a variable like `brace_re`, but then I got worried about the code getting too leggy.  It's a nested brace matching regex, based upon http://stackoverflow.com/a/6331667 .  If you have a preference between commenting, leaving it as is but assigning to a constant, expanding it using `/x`, etc., just let me know and I'll get it done tonight or tomorrow morning.

As for the rails 4.2.5.1 glob pattern, Rails is passing in the glob pattern in a call to `Dir[]`.  In my Rails app, the glob that gets passed in by Rails looks something like `image{.{en},}{.{html},}{+{},}{.{erb,builder,raw,ruby,coffee,haml},}`.  This new glob is probably part of the security fixes added in 4.2.5.1.  I suspect the glob is generated, and I haven't dug through the Rails source to figure out why they are generating it, what the individual pieces are for, etc.

The code that would normally process the glob pattern in the absence of `FakeFS` appears to be in `dir.c`, and I will be honest that I haven't dug into the Ruby source in an attempt to figure out how Ruby implements glob matching.  I will be honest - this is the first time I've seen the bash brace expansion syntax (at least I think that's what those braces in the glob are), and I didn't attempt to rethink the logic of the approach in `Globber#regexp` - I simply focused on getting it to work properly with nested braces and to escape the `+`, since I couldn't find a meaning for the `+` in glob syntax, but I didn't want it being interpreted by the regex engine.

**Comment by dtognazzini** [comment]
@tovodeverett Thanks for driving these changes!

I found another case that isn't supported by `Dir.glob`, added to `FakeFSTest`:

```ruby
  def test_dir_glob_handles_recursive_globs_bash_brace
    FileUtils.mkdir_p '/one/two/three'
    File.open('/zero.rb', 'w')
    File.open('/one/two/three/four.rb', 'w')
    File.open('/one/five.rb', 'w')
    assert_equal ['/zero.rb', '/one/five.rb'], Dir['{,*,*/*}.rb']
  end
```

Should pass, but fails with:
```
Minitest::Assertion: Expected: ["/zero.rb", "/one/five.rb"]
  Actual: ["/zero.rb"]
```

Bundler uses a glob pattern like this looking for gemspecs.

**Comment by tovodeverett** [comment]
@dtognazzini I've split this new issue off into https://github.com/fakefs/fakefs/issues/332 so it can be tracked separately.  The one you raise is going to be a lot more interesting!

**Comment by tovodeverett** [comment]
@smtlaissezfaire It appears that @dtognazzini has opened a whole bucket of worms.  I don't see a resolution to his issue that lies cleanly within the current architecture, and I'm volunteering to take on that rearchitecture and to put the pattern matching/globbing code on more solid footing.

I would appreciate it if you would comment on https://github.com/fakefs/fakefs/issues/332 and indicate whether you are willing to have me attack the problem.

If you agree, would you be willing to accept this current pull request as is (or close to as is) so we can resolve this set of issues?  The rearchitecture would render all of this code superfluous, but it's still a good fix for people that don't need https://github.com/fakefs/fakefs/issues/332.

**Comment by tovodeverett** [comment]
Superseded by https://github.com/fakefs/fakefs/pull/336.

**Pull request closed without merging**
